# NNIA Assignment 2
**DEADLINE: 17.11.2023 0800 CET**
- Philipp Hawlitschek 7043167 (phha00002)
- William LaCroix 7038732 (wila00001)
- Hours of work per person: 1

# Submission Instructions
**IMPORTANT** Please make sure you read the following instructions carefully. If you are unclear about any part of the assignment, ask questions **before** the submission deadline. All course-related questions can be addressed on the course **CMS Forum**.

* Assignments are to be submitted in a **team of 2-3**. It is fine to submit first **2** assignments without a team, but starting from the **3rd** assignment it is not allowed.
* Please include your **names**, **ID's**, **Teams usernames**, and **approximate total time spent per person** at the beginning of the Notebook in the space provided
* Make sure you appropriately comment your code wherever required.
* Your final submission should contain this completed Jupyter Notebook, and any necessary Python files. For this specific assignment, please, also include CSV file, generated by Pandas, and PNG picture from Matplotlib.
* Do **not** submit any data or cache files (e.g. `__pycache__`).
* Upload the **zipped** folder (`.zip` is the only accepted extension) in **CMS**.
* Only **one** member of the group should make the submission.
* **Important** please name the submitted zip folder as: `Name1_id1_Name2_id2(_Name3_id3).zip`. The Jupyter Notebook should also be named: `Name1_id1_Name2_id2.ipynb`. This is **very important** for our internal organization repeatedly students fail to do this.

<font color="red">Failure to follow the above instructions will result in point penalties at the discretion of the instructors.</font>


## 1 Linear Algebra (8 points)
In this chapter we ask you to do some Vector and Matrix operations.
There are some useful materials:
* [3Blue1Brown - Essense of Linear Algebra](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)
* [Linear Algebra chapter from the 'Deep Learning' book](https://www.deeplearningbook.org/contents/linear_algebra.html)

Of course, you can use any other references to complete this task.

## 1.1  Matrix operations (2 points)
Multiply the following matrices. If computation is impossible explain why.
1. $\begin{bmatrix} 1 & 1 \\ 2 & 2 \end{bmatrix} \cdot \begin{bmatrix} 2 & -1 \\ 2 & -1 \end{bmatrix}=\begin{bmatrix} 4 & -2 \\ 8 & -4 \end{bmatrix}$

2. $\begin{bmatrix} 2 & -1 \\ 2 & -1 \end{bmatrix} \cdot \begin{bmatrix} 1 & 1 \\ 2 & 2 \end{bmatrix}=\begin{bmatrix} 0 & 0 \\ 0 & 0 \end{bmatrix}$

3. $\begin{bmatrix} 1 & 2 & -1 \\ 1 & 0 & 1\end{bmatrix} \cdot \begin{bmatrix}1 & 3 & -2 \\ 2 & -2 & 0 \\ 4 & -1 & 2 \end{bmatrix}=\begin{bmatrix} 1 & 0 & -4 \\ 5 & 2 & 0\end{bmatrix}$

4. $\begin{bmatrix} -1 & 3 & 5 \\ 3 & 4 & 0 \end{bmatrix} \cdot \begin{bmatrix} 4 & 6 \\ 0 & 5 \end{bmatrix}=$ Not possible: $(m\times n_1)\cdot (n_2\times k), n_1\neq n_2$

$\renewcommand{\vect}[1]{\boldsymbol{#1}}$
## 1.2 Multiplication properties and types of matrices (4 point)
Provide a definition and example for the following matrices:
1. Transpose of a matrix: effectively swaps the indices of a matrix $\vect{A}_{ij}\to \vect{A}_{ji}$:
$$\vect{A}=\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix} \to \vect{A}^T=\begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}$$

2. Identity matrix: a square matrix with 1s on the diagonal and 0s everywhere else:
$$\vect{I}=\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{bmatrix}$$

3. Inverse of a matrix: $\vect{A}$ inverse $(\vect{A}^{-1})$ is defined such that $\vect{A}\cdot\vect{A}^{-1}=\vect{I}$:
$$\begin{bmatrix} 4 & 3 \\ 3 & 2 \end{bmatrix} \cdot \begin{bmatrix} -2 & 3 \\ 3 & -4 \end{bmatrix}=\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$$

4. Symmetric matrix: a matrix is symmetric if it is equal to its transpose (mirrored around the diagonal):
$$\vect{A}=\begin{bmatrix} 1 & 2 & 3 \\ 2 & 4 & 6 \\ 3 & 6 & 12\end{bmatrix}=\vect{A}^T$$


5. Orthogonal matrix: a square matrix where its inverse is equal to its transpose $(\vect{A}^{-1}=\vect{A}^T)$
$$\vect{A}=\begin{bmatrix} -1 & 0 \\ 0 & 1\end{bmatrix}=\vect{A}^T=\vect{A}^{-1};$$
$$\vect{A}\cdot\vect{A}^{-1}=\begin{bmatrix} 1 & 0 \\ 0 & 1\end{bmatrix}$$



Let $\vect{A}^{n \times n}$ be an orthogonal matrix, $\vect{B}^{m \times m}$ -- a symmetric matrix and $\vect{C}^{m \times n}$ -- a regular matrix, $\vect{I}$ -- identity matrix, and $\lambda$ -- a scalar.

For each expression choose its equivalent, show the intermediate steps, give the dimensions of the result.

* $(\vect{B}\lambda\vect{I})^T\vect{C}=\lambda\vect{BCI}$, dimension $(m\times n)$
$$steps:\space(\vect{B}\lambda\vect{I})^T\vect{C}=\vect{B}^T\lambda\vect{I}^T\vect{C}=\vect{B}\lambda\vect{I}\vect{C}=\lambda\vect{B}\vect{C}\vect{I}$$
  1. $\lambda \vect{CB}$
  2. $\vect{CB}^T  \lambda$
  3. $\lambda \vect{BCI}$
* $\vect{A}^{-1}(\vect{CA}^{-1})^T \lambda = \lambda \vect{C}^T$, dimension $(n\times m)$
$$steps:\space\vect{A}^{-1}(\vect{CA}^{-1})^T\lambda=\vect{A}^{-1}\vect{C}^T(\vect{A}^{-1})^T\lambda=\vect{A}^{-1}\vect{C}^T\vect{A}\lambda=\lambda \vect{C}^T$$
  1. $\lambda \vect{C}^T$
  2. $\lambda \vect{C}$
  3. $\vect{A}^T\vect{C}^T \lambda$
* $\vect{AA}^T\vect{B}^T\vect{C} = \vect{BC}$, dimension $(m\times n)$
$$steps:\space\vect{AA}^T\vect{B}^T\vect{C}=\vect{AA}^{-1}\vect{B}^T\vect{C}=\vect{I}\vect{B}^T\vect{C}=\vect{B}\vect{C}$$
  1. $\vect{CB}$
  2. $\vect{B}^{-1}\vect{C}$
  3. $\vect{BC}$

## 1.3 Eigenvalues (2 points)
Please, review slides and chapters 2.7 Eigendecomposition and 2.8 Singular value decomposition from [Deep Learning book](https://www.deeplearningbook.org/contents/linear_algebra.html) and do the following exercises:
1. Find a matrix $B \in {\rm I\!R}^{2 \times 2}$ whose eigenvalues are 1 and 4 with the corresponding eigenvectors $\begin{bmatrix} 3 \\ 1 \end{bmatrix}$ and $\begin{bmatrix} 2 \\ 1 \end{bmatrix}$ . Show your intermediate steps explicitly.

2. Let $A$ and $B$ be two $n \times n$ matrices. Show that if $\lambda$ is an eigenvalue of $AB$, then it is also an eigenvalue of $BA$.


## 2 Linear Algebra with [NumPy](https://numpy.org/) and [PyTorch](https://pytorch.org/docs/stable/index.html) (2 points)
You will explore more about `numpy` and `PyTorch` in the next exercise. For the last part of this exercise, please verify your calculations in Exercise 1.1 with NumPy and PyTorch. Feel free to check out these tutorials for [numpy](https://numpy.org/doc/stable/user/quickstart.html) and [PyTorch](https://caam37830.github.io/book/02_linear_algebra/pytorch.html).
### 2.1 Verify 1.1 with numpy and PyTorch

In [45]:
import numpy as np

def numpy_verify(A, B):
    try:
        print("A dot B =\n", np.matmul(A, B))
        print("")
    except ValueError:
        print("A dot B is not defined for")
        print("A =\n", A)
        print("and")
        print("B =\n", B)
        print("")

# 1.1.1
A = np.array([[1, 1], [2, 2]])
B = np.array([[2, -1], [2, -1]])
numpy_verify(A, B)

# 1.1.2
A = np.array([[2, -1], [2, -1]])
B = np.array([[1, 1], [2, 2]])
numpy_verify(A, B)

# 1.1.3
A = np.array([[1, 2, -1], [1, 0, 1]])
B = np.array([[1, 3, -2], [2, -2, 0], [4, -1, 2]])
numpy_verify(A, B)

# 1.1.4
A = np.array([[-1, -3, 5], [3, 4, 0]])
B = np.array([[4, 6], [0, 5]])
numpy_verify(A, B)


A dot B =
 [[ 4 -2]
 [ 8 -4]]

A dot B =
 [[0 0]
 [0 0]]

A dot B =
 [[ 1  0 -4]
 [ 5  2  0]]

A dot B is not defined for
A =
 [[-1 -3  5]
 [ 3  4  0]]
and
B =
 [[4 6]
 [0 5]]



In [46]:
import torch

def torch_verify(A, B):
    A = torch.Tensor(A)
    B = torch.Tensor(B)

    try:
        print("A dot B =\n", torch.mm(A, B))
        print("")
    except RuntimeError:
        print("A dot B is not defined for")
        print("A =\n", A)
        print("and")
        print("B =\n", B)
        print("")

# 1.1.1
A = np.array([[1, 1], [2, 2]])
B = np.array([[2, -1], [2, -1]])
torch_verify(A, B)

# 1.1.2
A = np.array([[2, -1], [2, -1]])
B = np.array([[1, 1], [2, 2]])
torch_verify(A, B)

# 1.1.3
A = np.array([[1, 2, -1], [1, 0, 1]])
B = np.array([[1, 3, -2], [2, -2, 0], [4, -1, 2]])
torch_verify(A, B)

# 1.1.4
A = np.array([[-1, -3, 5], [3, 4, 0]])
B = np.array([[4, 6], [0, 5]])
torch_verify(A, B)

A dot B =
 tensor([[ 4., -2.],
        [ 8., -4.]])

A dot B =
 tensor([[0., 0.],
        [0., 0.]])

A dot B =
 tensor([[ 1.,  0., -4.],
        [ 5.,  2.,  0.]])

A dot B is not defined for
A =
 tensor([[-1., -3.,  5.],
        [ 3.,  4.,  0.]])
and
B =
 tensor([[4., 6.],
        [0., 5.]])



In [9]:
print(torch.from_numpy(A))
print(torch.Tensor(A))

tensor([[-1, -3,  5],
        [ 3,  4,  0]], dtype=torch.int32)
tensor([[-1., -3.,  5.],
        [ 3.,  4.,  0.]])


### 2.2

With Numpy and PyTorch:
- Generate two rectangular random matrices $K$ and $L$ of shape such that they are multiplicable with $L \times K$
- Validate that $(K^T \times L^T)^T = L \times K$

In [47]:
# 2.2
K = np.random.rand(2, 5)
L = np.random.rand(5, 2)

np.matmul(K.T, L.T).T.tolist() == np.matmul(L, K).tolist()

True